### ISSUE TITLE
Coreos builds break because of ssh username

### ISSUE THREAD

**Issue by s4mur4i** [watson-platform/packer-builder-softlayer#8]
Hy,

Trying to create a base template for coreos build.
There is a bug currently in Softlayer that when creating a coreos device under the username/password information incorrect data will be shown.
username is root, and password is  xxxxxx
but the real username should be core with the above password.

when doing debug build I see:
2016/12/28 22:39:41 packer-builder-softlayer: 2016/12/28 22:39:41 Config: {PackerConfig:{PackerBuildName:softlayer PackerBuilderType:softlayer PackerDebug:true PackerForce:false PackerUserVars:map[]} Comm:{Type:ssh SSHHost: SSHPort:22 SSHUsername:root SSHPassword: SSHPrivateKey: SSHPty:false SSHTimeout:15m0s ....

It would be nice to have an ssh_username option for backup in such cases.
Issue is already raised to support.

**Comment by s4mur4i** [comment]
Ahh wait... I just realised that this is before machine is provisioned and static, is there any way to overwrite this option to have a different username?

**Comment by cmluciano** [comment]
This should be coming from packer overrides. Can you try setting it here https://www.packer.io/docs/templates/communicator.html

**Comment by s4mur4i** [comment]
Thanks, that solved my issue.
